# Generated by Django 4.2.3 on 2023-07-11 00:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("x11x_wagtail_blog", "0001_initial"),
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogArticlePage",
            fields=[
                (
                    "extensiblearticlepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="x11x_wagtail_blog.extensiblearticlepage",
                    ),
                ),
                ("body", wagtail.fields.StreamField([("text", wagtail.blocks.TextBlock())], use_json_field=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("x11x_wagtail_blog.extensiblearticlepage",),
        ),
    ]
